VS-24: Initial stable version
mongodb/mongo-csharp-analyzer pull request #1
Opened 2021-10-14 20:05 UTC by BorisDog

2021-11-11 20:05 UTC, JamesKovacs requested changes
Great first cut. Incorporating this feedback isn't a blocker to the beta release. It can be done post-beta1.

2021-11-11 20:05 UTC, JamesKovacs commented on tests/MongoDB.Analyzer.Tests/Infrastructure/TestCasesProvider.cs
> +                ToArray();
Our multi-line coding style has dot operator at the beginning of the line.

2021-11-11 20:05 UTC, JamesKovacs commented on tests/MongoDB.Analyzer.Tests.Common.TestCases/Linq/LinqExpressionsBasicTestCases.cs
> +        // aggregate([{ "$match" : { "Name" : "Bob", "Age" : { "$gt" : 16, "$lte" : 21 } } }])
As discussed in Slack, these comments would be better expressed as custom attributes. I believe you already changed this in a later PR, but wanted to confirm.

2022-01-11 00:51 UTC, BorisDog commented on src/MongoDB.Analyzer/Core/ReferencesProvider.cs
> +            string GetMongoDBDriverNetFrameworFullPath(string assemblyName)
Gone

2022-01-11 00:51 UTC, BorisDog commented on src/MongoDB.Analyzer/Core/Utilities/SymbolExtensions.cs
> +        public static bool ImplementsInterface(this ITypeSymbol typeSymbol, string interfaceName) =>
Good points:
1. Done
2. Done
3. We only need a type that implements this interface, or is the actual interface. In the case of a base class, all interfaces will be listed in `typeSymbol.Interfaces`. Changed the name to `ImplementsOrIsInterface`

2022-01-28 23:20 UTC, JamesKovacs approved these changes
LGTM.

N.B. The requested changes were made in another branch, which is why they're not showing up in this PR.

2022-02-05 00:10 UTC, BorisDog commented
Merge in [other PR](https://github.com/mongodb/mongo-csharp-analyzer/pull/3)

2022-02-05 00:10 UTC, closed without merging