VS-54: Support Linq Query syntax
mongodb/mongo-csharp-analyzer pull request #9
Opened 2022-07-07 02:25 UTC by Ravi-Raghavan

Support LINQ Query Syntax for the MongoDB C#/.NET Analyzer

2022-07-28 22:37 UTC, BorisDog requested changes

2022-07-28 22:37 UTC, BorisDog commented on tests/MongoDB.Analyzer.Tests.Common.TestCases/Linq/LinqQuery.cs
> +    public sealed class LinqQuery: TestCasesBase
Let's name it `LinqQuerySyntax`

2022-07-28 22:37 UTC, BorisDog commented on src/MongoDB.Analyzer/Core/Linq/LinqExpressionProcessor.cs
> +            if(node is not InvocationExpressionSyntax && node is not QueryExpressionSyntax)
Can this and the following `if` blocks be merged?

2022-07-28 22:37 UTC, BorisDog commented on src/MongoDB.Analyzer/Core/Linq/LinqExpressionProcessor.cs
> +            if(node is QueryExpressionSyntax queryNode)
Missing space here and other places.

2022-07-28 22:37 UTC, BorisDog commented on src/MongoDB.Analyzer/Core/Linq/LinqExpressionProcessor.cs
> +        //LINQ Method Syntax
Need this comment?

2022-07-28 22:37 UTC, BorisDog commented on src/MongoDB.Analyzer/Core/Linq/LinqExpressionProcessor.cs
> +            if(node is QueryExpressionSyntax queryExpressionSyntax)
This check is already done before.

2022-07-28 22:37 UTC, BorisDog commented on src/MongoDB.Analyzer/Core/Linq/LinqExpressionProcessor.cs
> +    }
Empty line missing.

2022-07-28 22:37 UTC, BorisDog commented on src/MongoDB.Analyzer/Core/Linq/LinqExpressionProcessor.cs
> +    private static bool PreanalyzeLinqQuerySyntax(SyntaxNode linqExpressionNode, SemanticModel semanticModel, List<InvalidExpressionAnalysisNode> invalidLinqExpressionNodes)
No way to combine with `PreanalyzeLinqExpression` ? Seems that they are almost the same.

2022-07-28 22:37 UTC, BorisDog commented on src/MongoDB.Analyzer/Core/Utilities/SyntaxNodeExtensions.cs
> +    public static SyntaxNode GetTopMostInvocationOrBinaryExpressionSyntax(SimpleNameSyntax identifier, IdentifierNameSyntax[] lambdaIdentifiers, IdentifierNameSyntax [] queryIdentifiers = null)
Do we really need to distinguish between lambdaIdentifiers and queryIdentifiers ?

2022-07-28 22:37 UTC, BorisDog commented on tests/MongoDB.Analyzer.Tests.Common.TestCases/Linq/LinqQuery.cs
> +            var query = from item in GetMongoQueryable()
Try having large difference between test cases, reflected in the test method name, for example `Query_Syntax_8` and `Query_Syntax_9` are practically identical.

2022-07-28 22:37 UTC, BorisDog commented on tests/MongoDB.Analyzer.Tests.Common.TestCases/Linq/LinqQuery.cs
> +        public void Query_Syntax_11()
Try eliminating the repeating prefix Query, and think about more meaningful names for test methods if possible.
Also need test cases for edge cases like:

1. Methods invocation `where Foo(something) `
2. `from item in q where Foo(item)`
3. Don't always use `queryable` name, as it matches the MQLGenerator variable.
4. Few queries in single methods
5. Not supported queries like `item.GetHashCode() == 123` and other.

2022-08-18 20:36 UTC, Ravi-Raghavan commented on src/MongoDB.Analyzer/Core/Linq/LinqExpressionProcessor.cs
> +        foreach (var node in root.DescendantNodes(descendToChildrenPredicate).OfType<ExpressionSyntax>())
Done

2022-08-18 20:36 UTC, Ravi-Raghavan commented on src/MongoDB.Analyzer/Core/Utilities/SymbolExtensions.cs
> +    public static bool ContainsQueryParameter(this ISymbol symbol, SyntaxNode parentNode)
Done

2022-08-18 22:45 UTC, merged